### ISSUE TITLE
HONEY vs. Mark

### ISSUE THREAD

**Issue by henry-luo** [honey/honey#2]
What do you think of [Mark](https://mark.js.org), a new notation that tries to unify JSON and XML?

I think one major missed-out feature from JSON (and many formats derived from JSON) is that it does not have an explicit name.

**Comment by rymohr** [comment]
Mark looks powerful but I've personally never felt hindered by HTML or JSON (aside from lack of comments).

As far as HONEY vs Mark, HONEY was designed to minimize intimidation of non-programmers by removing as much syntax as possible (even if that meant limiting the power of the language). Hard to compare the two since they serve totally separate goals.

Looks like a lot of great feedback in the HN thread:
https://news.ycombinator.com/item?id=16308581

**Comment by henry-luo** [comment]
Thanks for the comments!
